// ── PCI Company Knowledge Base ─────────────────────────────────────
// Comprehensive, authoritative data about Premier Choice International.
// Upgraded based on website scraping + PDFs (Company Profile & Coffee Book).

export const PCI_KNOWLEDGE = {
  company: {
    name: "Premier Choice International",
    shortName: "PCI",
    founded: 2011,
    foundedIn: "Dubai, UAE (by Amran Zia)",
    globalFootprint: "5,000,000+ square feet of development globally",
    employees: "150+ team of experts globally",
    certification: "ISO 9001:2015 (Quality Management Systems) for construction efficiency and customer satisfaction",
    philosophy: "Client-centric approach, delivering superior investment returns (ROI's), community building, and stress-free real estate experiences through complete end-to-end service.",
    globalPresence: ["Islamabad (Pakistan)", "Dubai (UAE)", "New York (USA)", "Alberta (Canada)"],
    totalProjects: "26+ development projects (13+ completed)",
    website: "https://premierchoiceint.com",
  },

  leadership: [
    { name: "Mr. Amran Zia", role: "Founder & CEO (21+ years hospitality & real estate experience, Alpina School of Hotel Management Switzerland graduate)" },
    { name: "Mahhad Imran", role: "Managing Director (Formerly PwC Dubai, LDA Capital Los Angeles, KSR New York; UCLA Honors Graduate)" },
    { name: "Shafqat Qadri", role: "Chief Financial Officer (Formerly PwC NY Audit/International Tax, VP Barclays NY & Toronto, Exec Director Arqaam Capital UAE)" },
    { name: "Mohsin Agha", role: "Director Projects (40+ years experience in CDA, POF, NDC, NWS Housing Society; Pride of Performance 2002 and Sitara-e-Imtiaz 2013 recipient)" },
    { name: "Syed Adeel Nasir", role: "Sr. Director Business Development (20+ years real estate/corporate BD experience with Zameen.com, Ufone, MTBC, J7 Group)" },
    { name: "Awais Qureshi", role: "Director Corporate Relations (Former PM at MUC Oil & Gas Fujairah, TAHTAN General Contracting Abu Dhabi)" },
    { name: "Azhar Amin", role: "Director Finance (Former CFO/Finance Director at FCL, Montgomery, KB & Kami Ventures USA, Al Nahar Group UAE)" },
    { name: "Fahad Qureshi", role: "Head of Sales (Former McKinsey CRM, Apple ME Expansion Manager, Faisal Town GM Sales & Marketing)" },
    { name: "Nawaz Mehmood", role: "Executive Director - Hospitality (32+ years hospitality experience across 3 continents; senior roles at Hyatt and Caesar's Palace)" },
    { name: "Imran Kiyani", role: "Property Facilitation Manager - Pakistan (Formerly Emaar Pakistan, Al Asmakh Facilities Management)" },
    { name: "Mohammad Jibran", role: "Property Manager (Experience with Carphone Warehouse UK, Rock Fall Property QAT, FF Steel PAK)" },
  ],

  pmoDepartments: [
    "Design Department — State-of-the-art Architectural, Structural and MEP engineering, headed by engineers registered with PCATP and PEC.",
    "Planning Department — Meticulous project life cycle planning for timely delivery.",
    "Procurement & Stores Department — Ensures timely procurement for uninterrupted project execution.",
    "Quantity Surveying Department — Handles project estimation, budgeting, and billing.",
    "Quality Assurance & Quality Control (QA/QC) — Multi-layered strict quality checks and controls (ISO 9001:2015 certified).",
    "Execution Supervision Department — Direct project monitoring by qualified Project Managers.",
    "Safety Department — Enforces mandatory safety protocols and safety gear on site.",
  ],

  contact: {
    email: "info@premierchoiceint.com",
    phones: {
      pakistanLandline: "+(92) 51 8738545 / 459",
      generalSales: "+92 301 123 3333",
      dubaiHeadOffice: "+971 4 591 7499",
    },
    offices: {
      pakistan: "Plot No. 67 A-1, Bahria Food Street, Bahria Springs North Commercial, Phase 7, Bahria Town, Islamabad, Pakistan",
      dubai: "Office 1013, Onyx Tower 1, The Greens, Dubai, United Arab Emirates",
    },
    businessHours: "Monday to Saturday: 9:00 AM to 8:00 PM",
  },

  projects: {
    completed: [
      {
        name: "Fortunato JVC",
        location: "Jumeirah Village Circle (JVC), Dubai, UAE",
        type: "Residential Complex",
        area: "650,000 sq. ft.",
        structure: "5 Floors",
        features: "Developed as part of Al-Tajir Real Estate, offering gym, swimming pool, 24/7 security",
        timeline: "Completed in 2014",
      },
      {
        name: "Stettler Crossroads Shopping Centre",
        location: "Stettler, Alberta (AB), Canada",
        type: "Strip Mall Commercial Development",
        area: "150,000 sq. ft.",
        features: "Houses various shopping outlets (e.g., Pet Valu, Sobeys Liquor) to facilitate community shopping",
        timeline: "Completed in 2012",
      },
      {
        name: "68 High Street",
        location: "Bahria Food Street, Phase 7, Bahria Town, Islamabad",
        type: "Mall (Luxury Retail & Dining)",
        area: "200,000 sq. ft.",
        structure: "LG + G + M + 4 Floors",
        features: "Dine-in and takeaway restaurants (such as Chaye Khana, Armani, Nike, Alcott), retail outlets, river-facing corniche boardwalk",
        timeline: "Completed in 2019",
      },
      {
        name: "Box Park",
        location: "Bahria Food Street, Phase 7, Bahria Town, Islamabad",
        type: "Mall & Flagship Commercial Strip",
        area: "130,000 sq. ft.",
        structure: "LG + G + M + 3 Floors",
        features: "Strip mall with major food outlets, shopping brands, entertainment facilities, features Corniche Walk on the Soan river-facing side",
        timeline: "Completed in 2017",
      },
      {
        name: "River Hills 1",
        location: "Bahria Town Phase 7, Islamabad",
        type: "Multi-story Residential Apartment Building",
        area: "165,000 sq. ft.",
        structure: "LG + G + 9 Floors",
        features: "Located next to Clock Tower roundabout, overlooking Soan River with stunning mountainous views",
        timeline: "Completed in 2015",
      },
      {
        name: "River Hills 2",
        location: "Bahria Town Phase 7, Islamabad",
        type: "Residential Apartment Building",
        area: "55,000 sq. ft.",
        structure: "LG + G + 8 + Penthouse",
        features: "Superior rental and investment opportunity matching River Hills 1 with value-addition modifications",
        timeline: "Completed in 2016",
      },
      {
        name: "River Hills 3",
        location: "Bahria Town Phase 7, Islamabad",
        type: "Residential & Commercial Complex",
        area: "60,000 sq. ft.",
        structure: "LG + G + 9 Floors",
        features: "9 floors of residential space with 2 commercial floors. Save Mart located just steps away",
        timeline: "Completed in 2018",
      },
      {
        name: "River Hills 4",
        location: "Bahria Town Phase 7, Islamabad",
        type: "Residential Apartment Building",
        area: "63,000 sq. ft.",
        structure: "LG + G + 9 Floors",
        features: "Facilities management by PCI, swift access to Save Mart, round-the-clock security",
        timeline: "Completed in 2019",
      },
      {
        name: "River Loft",
        location: "Bahria Intellectual Village, Phase 7, Islamabad",
        type: "Residential Apartment Complex",
        area: "252,000 sq. ft.",
        structure: "G + 3 + Penthouse",
        features: "Luxuriously spaced out complex made of 6 buildings with private parks, superior views, and 24/7 security",
        timeline: "Completed in 2020",
      },
      {
        name: "Grand Gallery",
        location: "Bahria Food Street, Phase 7, Bahria Town, Islamabad",
        type: "Luxury Shopping Mall",
        area: "30,000 sq. ft.",
        structure: "LG + G + M + 3 Floors",
        features: "Nestled between Box Park and 68 High Street, featuring a Pizza Hut, Mobile Expert, and extension of Corniche Walk",
        timeline: "Completed in 2021",
      },
    ],
    underConstruction: [
      {
        name: "Orchard Boulevard",
        location: "DHA Phase 1, Islamabad",
        type: "Mega Commercial & Residential Hub (Largest in the Twin Cities)",
        area: "4,000,000+ sq. ft.",
        approvedBy: "Defense Housing Authority (DHA) Approved",
        components: [
          "Grand Orchard (Residences & Mall) — 1,000,000+ sq. ft., 3 buildings, 4B+G+18 Floors, featuring Hilton Garden Inn",
          "Techno Park (Mall & Apartments) — High-tech shopping and residential facilities",
          "The Orchard Business Park — Prime office spaces and corporate zone",
          "The DHA Gateway — Premium commercial entryway development",
          "The Premier Corporate Avenue — Modern corporate spaces",
        ],
        amenities: [
          "Card-based community living (security, gym, parking, and room entry)",
          "4-layered security system",
          "Restaurants, shops & offices",
          "Gym & Spa, Swimming pool",
          "Tennis court, Kids play area",
          "Grade AAA parking facilities",
        ],
      },
      {
        name: "River Courtyard (Tower 1)",
        location: "Bahria Intellectual Village, Phase 7, Bahria Town, Islamabad",
        type: "Mixed-use High-rise (Residential + Wyndham Serviced Apartments)",
        area: "450,000 sq. ft.",
        structure: "2B + LG + G + 15 Floors (14-story ultra-luxury development)",
        partnership: "Licensed by Ramada by Wyndham — Serviced Apartments",
        amenities: [
          "The Rohtas Thermal Club (Pakistan's first thermal club)",
          "Indoor temperature-controlled pool, gym, health & spa",
          "Tennis, basketball, and skating courts",
          "Walking/jogging tracks, Corniche Walk access",
          "Fine-dining restaurants, gated security with 24/7 CCTV",
        ],
        proximity: "1 min from DHA-1, 3 min from Main GT Road, 12 min from Saddar Rawalpindi",
        timeline: "Launched 2021",
      },
      {
        name: "River Courtyard II (Tower 2)",
        location: "Bahria Intellectual Village, Phase 7, Islamabad",
        type: "Resort-style Serviced & Residential Apartments",
        area: "400,000 sq. ft.",
        structure: "3B + G + 18 + Amenities Floor",
        features: "Extension of River Courtyard, aiming to transform River Front into a premier resort-style destination",
        timeline: "Launched 2023",
      },
      {
        name: "Gateway",
        location: "Jumeirah Village Circle (JVC), District 10, Dubai, UAE",
        type: "Mixed-Use Technology-driven Residential Tower",
        area: "300,000 sq. ft.",
        structure: "G + 4P + 11 + Rooftop Recreational Area",
        smartFeatures: [
          "Amazon Alexa smart home integration, Orvibo smart technology, card access control",
          "Rooftop infinity pool, rooftop cinema, sky BBQ deck",
          "Highest Padel Tennis Court in Dubai",
          "Automated human-free grocery store, dedicated co-working area",
        ],
        paymentPlans: "Flexible 60/40 or 50/50 plans, ~10% down payment",
        timeline: "Launched 2023",
      },
      {
        name: "Buraq Heights",
        location: "Bahria Intellectual Village, Phase 7, Islamabad",
        type: "Resort-Style Serviced Apartments & Commercial Tower",
        area: "200,000 sq. ft.",
        structure: "2B + G + 11 + Penthouse",
        features: "Resort-style facilities managed by Premier Hospitality, river-front views",
        timeline: "Launched 2022",
      },
      {
        name: "Barari Views Limited",
        location: "Majan, Al Barari, Dubai, UAE",
        type: "Residential Vertical Living",
        area: "56,000 sq. ft.",
        structure: "G + 6 Floors",
        features: "Spacious vertical living in the heart of the ultra-luxury Al Barari community",
        timeline: "Launched 2022",
      },
      {
        name: "South Lofts I",
        location: "Dubai South, Dubai, UAE",
        type: "Residential Development",
        area: "120,000+ sq. ft.",
        features: "Designed for young professionals; over 26,000 sq. ft. of dedicated amenities including infinity pool, indoor/outdoor gym, Padel court, wellness zone, co-working, and jogging track",
        timeline: "Launched 2024",
      },
      {
        name: "South Lofts II",
        location: "Dubai South, Dubai, UAE",
        type: "Residential Development",
        area: "135,000+ sq. ft.",
        features: "Continuing the South Lofts contemporary residential vision with wellness and community focus",
        timeline: "Launched 2024",
      },
      {
        name: "Spring Arch",
        location: "District Commercial, Bahria Town Phase 8, Islamabad",
        type: "Commercial & Residential",
        area: "80,000 sq. ft.",
        structure: "LG + G + 8 Floors",
        features: "Sleek and innovative community spaces with outstanding connectivity to Bahria Food Street, DHA, and Ring Road",
        timeline: "Launched 2022",
      },
      {
        name: "Box Park II",
        location: "Bahria Food Street, Phase 7, Bahria Town, Islamabad",
        type: "Commercial Development",
        area: "30,000 sq. ft.",
        structure: "LG + G + M + 3 Floors",
        features: "Based on the successful model of Box Park I, providing commercial spaces for live, work, and retail",
        timeline: "Launched 2022",
      },
      {
        name: "Box Park III",
        location: "Bahria Phase 7, Islamabad",
        type: "Commercial & Corporate Tower",
        area: "20,000 sq. ft.",
        structure: "G1 + G2 + M + 3 Floors",
        features: "Prime spaces for commercial and corporate activity next to Box Park I & II",
        timeline: "Launched 2024",
      },
      {
        name: "River Hills 5",
        location: "DHA Phase 1, Sector F, Islamabad",
        type: "Residential Apartment Tower",
        area: "200,000 sq. ft.",
        structure: "3B + G + 12 + Penthouse",
        features: "Upgradation of the River Hills concept with improved facilities walking distance from River Hills 1-4",
        timeline: "Launched 2023",
      },
      {
        name: "Boulevard Central",
        location: "Islamabad, Pakistan",
        type: "Residential & Commercial",
        timeline: "Launched 2023",
      },
      {
        name: "Corporate Avenue",
        location: "Islamabad, Pakistan",
        type: "Corporate & Commercial",
        timeline: "Launched 2024",
      },
      {
        name: "South Loft",
        location: "Dubai, UAE",
        type: "Residential elevated co-living",
        timeline: "Target completion 2026",
      },
    ],
  },

  faqs: [
    {
      q: "What does PCI do?",
      a: "Premier Choice International is a vertically integrated real estate development company. We specialize in Investment Management; Design, Project & Development Management; Rental & Leasing; and Property & Facilities Management across Pakistan, the UAE, Canada, and the USA.",
    },
    {
      q: "Where are PCI's offices?",
      a: "PCI has offices in Islamabad, Pakistan (Bahria Food Street, Phase 7, Bahria Town) and Dubai, UAE (Office 1013, Onyx Tower 1, The Greens).",
    },
    {
      q: "Who is in the executive leadership team?",
      a: "The leadership team includes Mr. Amran Zia (Founder & CEO), Mahhad Imran (Managing Director), Shafqat Qadri (CFO), Mohsin Agha (Director Projects), Syed Adeel Nasir (Sr. Director Business Development), Awais Qureshi (Director Corporate Relations), Azhar Amin (Director Finance), and Fahad Qureshi (Head of Sales). Hospitality is led by Nawaz Mehmood (Executive Director).",
    },
    {
      q: "What is PCI's total footprint?",
      a: "PCI has over 5 million square feet of development globally, with 26+ development projects in its portfolio, including 13+ completed projects.",
    },
    {
      q: "What international partnerships does PCI have?",
      a: "PCI is partnered with Ramada by Wyndham for River Courtyard (Pakistan's first internationally approved serviced apartments) and Hilton Garden Inn for Grand Orchard in DHA Phase 1, Islamabad.",
    },
    {
      q: "What is Orchard Boulevard?",
      a: "Orchard Boulevard is a massive 4,000,000+ sq. ft. DHA-approved commercial and residential hub in DHA Phase 1, Islamabad. It comprises Grand Orchard, Techno Park, The Orchard Business Park, The DHA Gateway, and The Premier Corporate Avenue, featuring a card-based community, 4-layered security, and grade AAA parking.",
    },
    {
      q: "Tell me about Dubai projects.",
      a: "Completed Dubai projects include Fortunato in JVC (650,000 sq. ft., completed 2014). Active projects under construction include JVC Gateway (smart home technology, padel tennis, rooftop cinema), Barari Views Limited (Majan, Al Barari), South Lofts I & II (Dubai South), and South Loft (target completion 2026).",
    },
    {
      q: "Is PCI ISO certified?",
      a: "Yes, PCI holds ISO 9001:2015 certification for Quality Management Systems, reflecting our commitment to construction efficiency, high-quality standards, and customer satisfaction.",
    },
    {
      q: "What is The Rohtas Thermal Club?",
      a: "The Rohtas Thermal Club at River Courtyard (Wyndham Ramada) is Pakistan's first-ever thermal club, featuring a full health and spa experience, indoor temperature-controlled swimming pool, and premium wellness facilities.",
    },
    {
      q: "What is the cancellation/refund policy?",
      a: "For payment concerns, cancellations, or refund queries, please contact the Customer Care team directly at +92 301 123 3333 or email info@premierchoiceint.com. A dedicated care specialist will assist you.",
    },
  ],
} as const;
